spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: user-service
    openfeign:
      circuitbreaker:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        record-failure-predicate: com.sunny.userservice.client.circuitbreaker.ExceptionRecordFailurePredicate
#    instances:
#      default:
#        base-config: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, circuitbreakers

feign-endpoint:
