spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: user-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 0

jwt:
  secret: aslkdnbvapdcnvakldsvfalwkr0134dakfdsakjb2152ereonfp1nf1idnvpasclvkxcv
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000