spring:
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    config:
      name: project-service
    loadbalancer:
      cache:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        record-failure-predicate: com.sunny.projectservice.common.client.circuitbreaker.ExceptionRecordFailurePredicate


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers


feign-endpoint: