spring:
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: project-service
    loadbalancer:
      cache:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 0