spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/minsik2434/Sunny.git
          default-label: develop
          search-paths: resource/

server:
  port: 8888
